[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "ttf-dejavu",
  "glib",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "libdrm",
  "libxkbcommon",
  "mesa",
  "libGL"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
